### ISSUE TITLE
Group stream IDs by vnodes when reading from CDC log

### ISSUE THREAD

**Issue by piodul** [piodul/scylla-cdc-rust#14]
Depends on #4.

In order to reduce the number of concurrent reads, it's better to query CDC log by groups of streams which have the same vnode ID. In the `system_distributed.cdc_streams_descriptions_v2` table, streams are already grouped by vnode, each row corresponding to a separate vnode.

We should make sure that each stream reader is querying such a group of streams, not single streams.

**Comment by macher259** [comment]
Currently I am flattening the vector of sets of stream ids in `GenerationFetcher`.
Should I not flatten it and change return type to `Vec<Vec<StreamID>>` or create a new function that return streams grouped by vnode?

**Comment by piodul** [comment]
@macher259 Returning a `Vec<Vec<StreamID>>` without flattening should be OK.

**Comment by piodul** [comment]
Done in 0fb97433069787c15eef781805b98194cd882fc4
