### ISSUE TITLE
Implement a simple CDC log printer

### ISSUE THREAD

**Issue by piodul** [piodul/scylla-cdc-rust#4]
Depends on #2 and #3

The task is to implement a simple version of the library which reads data from a specified CDC log table and prints it to the standard output. The library should start reading starting from a point of time specified by the user and should correctly handle generation changes. The library should process data from all streams.

Note: although in #3 it is mentioned that the stream reader should be able to read from multiple streams at once, I recommend creating a separate stream reader for each stream for now. It is beneficial to read from multiple streams which belong to a single vnode, but it can be done as a later optimization.

**Comment by Ponewor** [comment]
What is the expected behaviour of the library when there is no generation for a given point of time?

**Comment by piodul** [comment]
It should start consuming from the beginning of the generation which has the lowest timestamp. If there are no generations at all, it should wait in a loop, periodically checking for the first generation to appear.

You can use generation component's method which fetches a list of all generations and then choose the lowest one. I know that it isn't particularly efficient, but let's use the interface defined in #2 for now. We can optimize it later, after this issue is closed.
