### ISSUE TITLE
Create black-box end-to-end library test

### ISSUE THREAD

**Issue by haaawk** [piodul/scylla-cdc-rust#44]
Create a test that works with a Scylla cluster and does the following:

1. Generates a list of operations
2. Registers a consumer with a scylla-cdc-rust library that logs all changes it consumes maintaining the order in which they were consumed.
3. Send all the operations from (1) to Scylla server
4. Check that the operations consumed in (2) are the same as list from (1). That means no operation was missed and all operations were consumed in the same order as they were issued to the server.

**Comment by piodul** [comment]
@procrastinationfighter
