### ISSUE TITLE
Explore the replicator integration test and adapt it to our replicator

### ISSUE THREAD

**Issue by piodul** [piodul/scylla-cdc-rust#45]
The task is to:

1. Check out the existing replicator test which was used during development of Java and Go libraries
2. Run the test with Java or Go replicator, whatever is easier (probably Java)
3. Adapt the test so that it is able to run with our version of the replicator

Test: https://github.com/kbr-/scylla-test

**Comment by macher259** [comment]
I have a problem with running these tests.
To run them, according to README, I have to use `scylla-migrate` from `https://github.com/scylladb/scylla-migrate.git`

I can't access this repo. Either it is a private repository or it doesn't exist at all.
Scylla has repo with similar name [scylla-migrator](https://github.com/scylladb/scylla-migrator), but I am not sure if this is the right one.

**Comment by Ponewor** [comment]
The adapted version can be found here https://github.com/Ponewor/scylla-test
Mode and consitency level settings we removed as we do not support them (yet) in our version of the replicator.

It was tested against Java version and it went smoothly as expected.
It was tested against the version from https://github.com/Ponewor/scylla-cdc-rust/tree/executable_replicator and it also looks fine.

What is the Definition of Done here?

**Comment by piodul** [comment]
The only remaining thing needed to consider the task done is to upstream the changes in `scylla-test` which were needed for our version of the replicator to run.

**Comment by piodul** [comment]
The PR has been submitted: https://github.com/kbr-/scylla-test/pull/3 , closing
