### ISSUE TITLE
Improve the printer

### ISSUE THREAD

**Issue by procrastinationfighter** [piodul/scylla-cdc-rust#83]
As for now, the printer exists in a form of library. There are two things that should be done:

- Add prettier printing, because now it only prints the cql information from rows.
- Make it an executable, so that it can serve as an example of how to build an application using our library.

**Comment by piodul** [comment]
Regarding the first bullet point, the most important thing is to print all data from CDCRow, i.e. first, cdc-specific columns independent from the schema of the base table (`cdc$stream_id`, `cdc$time`, etc.), then the columns dependent on the base schema (`x`, `cdc$deleted_x` (if exists), `cdc$deleted_elements` (if exists) for `x` in base table columns).

The precise format is not important, just that it's easy to associate column names with printed values (e.g. `column_name: column_value, ...`).

**Comment by procrastinationfighter** [comment]
@piodul this issue got closed automatically, but only part of it was fixed (the pretty printing is still to be done), shall we open another issue?

**Comment by piodul** [comment]
> @piodul this issue got closed automatically, but only part of it has been fixed (the pretty printing is still to be done), shall we open another issue?

Yes, please.
