### ISSUE TITLE
Log reading benchmark

### ISSUE THREAD

**Issue by piodul** [piodul/scylla-cdc-rust#87]
We need to measure how fast the library is able to consume data and how much resources it uses.

Let's run a benchmark which loads a fixed amount of data and then runs a scylla-cdc-rust application which just reads the whole log (from given timestamp up to given timestamp) without doing anything else.

We need:

1. A scylla-cdc-rust application which reads data between given timestamps. The printer can serve as a base (by that I mean take the logic and remove printing - the consumers can be just a no-op, maybe they can just count the number of rows read).
	- We also need a similar application based on scylla-cdc-java so that we can compare the performance of both implementations
	- As a minimal validation, let's count the number of read rows and print it at the end
2. Create a test script which performs the following benchmark (it should assume that the cluster is created and should be provided with a contact IP):
	1. Create a table X with CDC enabled
	2. Write some data with scylla-bench with sequential distribution. The amount of written rows should be configurable.
	3. Run the log reading application
	4. The log reading program should be run using the [GNU time](https://www.gnu.org/software/time/) program (e.g. `/usr/bin/time -v ./log-reader`) so that we collect interesting statistics such as wall/user/system time, peak memory usage etc.

**Comment by procrastinationfighter** [comment]
I can't find how to read between timestamps in `scylla-cdc-java`. I would expect it to be in the [builder](https://github.com/scylladb/scylla-cdc-java/blob/f67d083fccf763f6ba8e35047996b6baff81b5c0/scylla-cdc-lib/src/main/java/com/scylladb/cdc/lib/CDCConsumer.java#L93), like in our case, but I can't find it there. The tutorial doesn't mention it either - is it even possible? 
The situation is a bit better in the golang version of the library - one can specify [here](https://pkg.go.dev/github.com/scylladb/scylla-cdc-go?utm_source=godoc#AdvancedReaderConfig) how far into the past should the reader delve. 

As for Rust version - I've already created a modified version of the printer that takes two bonus arguments: start and end datetime.

**Comment by piodul** [comment]
I talked with @avelanarius (who maintains the scylla-cdc-java library) and it looks like you are right that scylla-cdc-java does not have the concepts of start or end timestamps. We will have to modify the benchmark a bit.

First, by default the library starts reading data from the beginning of the first generation. We can insert data shortly after the cluster was initialized and start reading from the very beginning in the scylla-cdc-rust benchmark, too.

Second, we can count rows and stop the log reader immediately after reaching the desired number of rows. It will probably be the easiest to have a shared atomic counter and stop the library when the counter reaches the target count.

As for the validation (we were supposed to count the number of rows read): instead, we can compute some checksum of the data, e.g. compute the sum of all encountered clustering key values.

**Comment by procrastinationfighter** [comment]
The benchmark: https://github.com/procrastinationfighter/scylla-cdc-rust-benchmark
Results (rust, go, java): [results.zip](https://github.com/piodul/scylla-cdc-rust/files/9104387/results_with_go.zip)
